### ISSUE TITLE
Wanting to contribute to appwrite

### ISSUE THREAD

**Issue by PJayakrishnan** [appwrite/playground-for-dotnet#12]
@eldadfux  I am a newbie to Open source and interested in contributing to appwrite. I have experience in contributing to some other projects. Is there anything in this repository I can contribute to as a beginner? Any suggestions?

**Comment by stnguyen90** [comment]
@PJayakrishnan no need to create an issue to ask a question like this. We would love you to check out some of our other open issues [here](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aappwrite+user%3Autopia-php+no%3Aassignee+label%3Ahacktoberfest) and join us on [Discord](https://appwrite.io/discord) if you need help finding some. In general, finding issues labeled `good first issue` is a good start.
