### ISSUE TITLE
Upgrade our issue templates to use GitHub issue forms ✍️

### ISSUE THREAD

**Issue by Meldiron** [appwrite/playground-for-dotnet#5]
# Introduction

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

Appwrite currently uses the older [issue template format](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). Your task is to create **GitHub issue forms** for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ] Fork & clone this repository
- [ ] Prepare **bug report** issue form in `.github/ISSUE_TEMPLATE/bug.yaml`
- [ ] Prepare **documentation** issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare **feature request** issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to **master** and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

Are you ready to work on this issue? 🤔 Let us know, and we will assign it to you 😊

**Happy Appwriting!**

**Comment by Obnoxious-coder** [comment]
Kindly assign this to me

**Comment by aniketh-varma** [comment]
Hello, I would like to work on this issue. Please assign me the same.

**Comment by TorstenDittmann** [comment]
@Obnoxious-coder We will start assigning as soon as we kick off Hacktoberfest at 12 am EST 👍🏻

@aniketh-varma Please do not try to claim too many issues for yourself. We want everyone to have the chance to contribute to our projects.

**Comment by Christian-Oleson** [comment]
Oh shoot, I only saw the first part of this request (above) and did not refresh the page to see that there were folks requesting to be assigned. I also still see it is unassigned. @Meldiron, does this cause any issue?

**Comment by christyjacob4** [comment]
@Obnoxious-coder All the best :rocket:

**Comment by christyjacob4** [comment]
@Christian-Oleson  We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

**Comment by Christian-Oleson** [comment]
> @Christian-Oleson We would love you to check out some of our other open issues and join us on [Discord](https://appwrite.io/discord) if you need help finding some.

I get an error when trying to join your discord:
"Unable to accept invite"

**Comment by christyjacob4** [comment]
@Christian-Oleson  it does work. I can share the link again https://appwrite.io/discord

**Comment by Christian-Oleson** [comment]
> @Christian-Oleson it does work. I can share the link again https://appwrite.io/discord

It's just me then, sadly. No worries.

**Comment by christyjacob4** [comment]
Thank you so much for the contribution! The changes have been merged and will be released soon
